CREATE TABLE "Users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" text UNIQUE,
  "password_hash" text
);

CREATE TABLE "Workouts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer,
  "startTime" timestamp DEFAULT 'now()',
  "endTime" timestamp,
  "name" text
);

CREATE TABLE "Exercises" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text
);

CREATE TABLE "WorkoutLog" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "workoutId" integer,
  "exerciseId" integer
);

CREATE TABLE "Sets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "weight" decimal,
  "reps" integer,
  "workoutLogId" integer
);

CREATE TABLE "WorkoutTemplates" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "userId" integer,
  "name" text
);

CREATE TABLE "WorkoutTemplateExercises" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "workoutTemplateId" integer,
  "exerciseId" integer
);

CREATE TABLE "WorkoutTemplateSets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "workoutTemplateExerciseId" integer,
  "reps" integer,
  "weight" decimal
);

ALTER TABLE "Workouts" ADD FOREIGN KEY ("userId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WorkoutLog" ADD FOREIGN KEY ("workoutId") REFERENCES "Workouts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WorkoutLog" ADD FOREIGN KEY ("exerciseId") REFERENCES "Exercises" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Sets" ADD FOREIGN KEY ("workoutLogId") REFERENCES "WorkoutLog" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WorkoutTemplates" ADD FOREIGN KEY ("userId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WorkoutTemplateExercises" ADD FOREIGN KEY ("workoutTemplateId") REFERENCES "WorkoutTemplates" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WorkoutTemplateExercises" ADD FOREIGN KEY ("exerciseId") REFERENCES "Exercises" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WorkoutTemplateSets" ADD FOREIGN KEY ("workoutTemplateExerciseId") REFERENCES "WorkoutTemplateExercises" ("id") DEFERRABLE INITIALLY IMMEDIATE;
