CREATE TABLE "Users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" text UNIQUE,
  "passwordHash" text
);

CREATE TABLE "Exercises" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text UNIQUE
);

CREATE TABLE "WorkoutTemplates" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text
);

CREATE TABLE "WorkoutTemplateExercises" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "exerciseId" integer,
  "workoutTemplateId" integer
);

CREATE TABLE "WorkoutTemplateSets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reps" integer,
  "weight" integer,
  "workoutTemplateExerciseId" integer
);

CREATE TABLE "Workouts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text,
  "startTime" timestamp DEFAULT (now()),
  "endTime" timestamp,
  "userId" integer,
  "workoutTemplateId" integer
);

CREATE TABLE "WorkoutExercises" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "exerciseId" integer,
  "workoutId" integer
);

CREATE TABLE "WorkoutSets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "reps" integer,
  "weight" integer,
  "order" integer,
  "workoutExerciseId" integer
);

ALTER TABLE "WorkoutTemplateExercises" ADD FOREIGN KEY ("exerciseId") REFERENCES "Exercises" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WorkoutTemplateExercises" ADD FOREIGN KEY ("workoutTemplateId") REFERENCES "WorkoutTemplates" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WorkoutTemplateSets" ADD FOREIGN KEY ("workoutTemplateExerciseId") REFERENCES "WorkoutTemplateExercises" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Workouts" ADD FOREIGN KEY ("userId") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Workouts" ADD FOREIGN KEY ("workoutTemplateId") REFERENCES "WorkoutTemplates" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WorkoutExercises" ADD FOREIGN KEY ("exerciseId") REFERENCES "Exercises" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WorkoutExercises" ADD FOREIGN KEY ("workoutId") REFERENCES "Workouts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "WorkoutSets" ADD FOREIGN KEY ("workoutExerciseId") REFERENCES "WorkoutExercises" ("id") DEFERRABLE INITIALLY IMMEDIATE;
